joy_node:
  deadzone: 0.01
  autorepeat_rate: 100
  coalesce_interval: 0.01

teleop:
  # Default mode - Stop for safety
  default:
    type: topic
    is_default: true
    message_type: std_msgs/Bool
    topic_name: /Safe
    message_value:
      -
        target: data
        value: false

  # Enable Human control by holding Left Bumper
  human_control_a:
    type: topic
    message_type: vesc_msgs/VescCtrlStamped
    topic_name: /vesc/ctrl
    deadman_buttons: [4]
    message_value:
      -
        target: control.mode
        value: 2
    axis_mappings:
      -
        axis: 1
        target: control.current
        scale: 30.0                  # joystick will command plus or minus 2 meters / second
        offset: 0 #0.10
      -
        axis: 3
        target: control.servo
        scale: 0.34               # joystick will command plus or minus ~20 degrees steering angle
        offset: -0.04021

  # Enable Human control by holding Right Bumper
  human_control_b:
    type: topic
    message_type: vesc_msgs/VescCtrlStamped
    topic_name: /vesc/ctrl
    deadman_buttons: [5]
    message_value:
      -
        target: control.mode
        value: 3
    axis_mappings:
      -
        axis: 1
        target: control.speed
        scale: 5.0                  # joystick will command plus or minus 2 meters / second
        offset: 0 #0.10
      -
        axis: 3
        target: control.servo
        scale: 0.68               # joystick will command plus or minus ~20 degrees steering angle
        offset: -0.04021

  human_control_c:
    type: topic
    message_type: std_msgs/Bool
    topic_name: /Safe
    deadman_buttons: [0]
    message_value:
      -
        target: data
        value: true
